services:
  mongodb:
    image: mongo:7-jammy

    container_name: mongodb_GenDrive

    ports:
      - "27018:27017"

    volumes:
      - mongodbData:/data/db

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

    networks:
      - backend
    
    restart: always




networks:
  backend:

volumes:
  mongodbData: